language: cpp
compiler: gcc

matrix:
  include:
    ####################### Linux #######################
    - os: linux
      dist: trusty
      sudo: required
      env:
        - qtenv: /opt/qt511/bin/qt511-env.sh
        - qtpkg: "'qt511-meta-full mesa-common-dev libgl1-mesa-dev'"
        - qtppa: ppa:beineri/opt-qt-5.11.1-bionic
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7

before_install:
  ### Create aliases for checking variables
  - function run() {
      if [ "$1" = "false" ]; then
        return 0;
      fi;
      shift;
      "$@";
    }
  - export isLinux=$( [[ "$TRAVIS_OS_NAME" == "linux" ]] && echo true || echo false )
  ### Version names
  - if [ -z "${TRAVIS_TAG}" ]; then
      export TRAVIS_VERSION="branch-${TRAVIS_BRANCH}";
      export VERSION="${TRAVIS_BRANCH}";
      if [ "${TRAVIS_BRANCH}" == "master" ]; then export VERSION="9999"; fi;
    else
      export TRAVIS_VERSION="${TRAVIS_TAG}";
      export VERSION="${TRAVIS_TAG#v}";
    fi
  - run $isLinux export PREFIX=slaq-${TRAVIS_VERSION}-linux-x86_64
  ### Linux
  - run $isLinux sudo add-apt-repository -y ${qtppa}
  - run $isLinux sudo apt-get update

install:
  ### Linux
  # Install dependencies
  - run $isLinux sudo apt-get install -y --force-yes ${qtpkg}

script:
  - run $isLinux source ${qtenv}
  - qmake -r
  - make

after_success:
  # Linux

